In [3]:
import torch
import numpy as np
import pandas as pd
import glob
import os
from sklearn.decomposition import PCA, KernelPCA

from torch.utils.data import TensorDataset, DataLoader, Dataset
from sklearn.model_selection import train_test_split
from torch import nn
from torch import optim
import torchvision.transforms as tr
import matplotlib.pyplot as plt

import time

In [4]:
path = 'C:/Users/kbj/Downloads/data/train/x/'
data_train_x_list = os.listdir('C:/Users/kbj/Downloads/data/train/x/')
path = 'C:/Users/kbj/Downloads/data/train/x/'
x_train_mean = np.array([])
x_train_var = np.array([])
x_train_std = np.array([])
x_train_max = np.array([])
x_train_min = np.array([])

for i in data_train_x_list:
    df = pd.read_csv(path+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    x_train_mean = np.append(x_train_mean, mean)
    x_train_var = np.append(x_train_var, var)
    x_train_std = np.append(x_train_std, std)
    x_train_max = np.append(x_train_max, max)
    x_train_min = np.append(x_train_min, min)

x_train_feature = np.concatenate((x_train_mean.reshape(-1,1), x_train_var.reshape(-1,1), x_train_std.reshape(-1,1), x_train_max.reshape(-1,1), x_train_min.reshape(-1,1)), axis=1)
x_train_feature.shape

path = 'C:/Users/kbj/Downloads/data/train/y/'
data_train_y_list = os.listdir('C:/Users/kbj/Downloads/data/train/y/')
path = 'C:/Users/kbj/Downloads/data/train/y/'
y_train_mean = np.array([])
y_train_var = np.array([])
y_train_std = np.array([])
y_train_max = np.array([])
y_train_min = np.array([])

for i in data_train_y_list:
    df = pd.read_csv(path+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    y_train_mean = np.append(y_train_mean, mean)
    y_train_var = np.append(y_train_var, var)
    y_train_std = np.append(y_train_std, std)
    y_train_max = np.append(y_train_max, max)
    y_train_min = np.append(y_train_min, min)

y_train_feature = np.concatenate((y_train_mean.reshape(-1,1), y_train_var.reshape(-1,1), y_train_std.reshape(-1,1), y_train_max.reshape(-1,1), y_train_min.reshape(-1,1)), axis=1)
y_train_feature.shape

path = 'C:/Users/kbj/Downloads/data/train/z/'
data_train_z_list = os.listdir('C:/Users/kbj/Downloads/data/train/z/')
path = 'C:/Users/kbj/Downloads/data/train/z/'
z_train_mean = np.array([])
z_train_var = np.array([])
z_train_std = np.array([])
z_train_max = np.array([])
z_train_min = np.array([])

for i in data_train_z_list:
    df = pd.read_csv(path+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    z_train_mean = np.append(z_train_mean, mean)
    z_train_var = np.append(z_train_var, var)
    z_train_std = np.append(z_train_std, std)
    z_train_max = np.append(z_train_max, max)
    z_train_min = np.append(z_train_min, min)

z_train_feature = np.concatenate((z_train_mean.reshape(-1,1), z_train_var.reshape(-1,1), z_train_std.reshape(-1,1), z_train_max.reshape(-1,1), z_train_min.reshape(-1,1)), axis=1)
z_train_feature.shape

path = 'C:/Users/kbj/Downloads/data/train/e/'
data_train_e_list = os.listdir('C:/Users/kbj/Downloads/data/train/e/')
path = 'C:/Users/kbj/Downloads/data/train/e/'
e_train_mean = np.array([])
e_train_var = np.array([])
e_train_std = np.array([])
e_train_max = np.array([])
e_train_min = np.array([])

for i in data_train_e_list:
    df = pd.read_csv(path+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    e_train_mean = np.append(e_train_mean, mean)
    e_train_var = np.append(e_train_var, var)
    e_train_std = np.append(e_train_std, std)
    e_train_max = np.append(e_train_max, max)
    e_train_min = np.append(e_train_min, min)

e_train_feature = np.concatenate((e_train_mean.reshape(-1,1), e_train_var.reshape(-1,1), e_train_std.reshape(-1,1), e_train_max.reshape(-1,1), e_train_min.reshape(-1,1)), axis=1)
e_train_feature.shape

#xyz_train_feature = np.sqrt(np.square(x_train_feature[:,0])+np.square(y_train_feature[:,0])+np.square(z_train_feature[:,0]))
#xyz_train_feature = xyz_train_feature.reshape(-1,1)
#all_train_feature = np.concatenate((x_train_feature, y_train_feature, z_train_feature, e_train_feature, xyz_train_feature), axis=1)
all_train_feature = np.concatenate((x_train_feature, y_train_feature, z_train_feature, e_train_feature), axis=1)
all_train_feature.shape

train_label = pd.read_csv('C:/Users/kbj/Downloads/data/train/train_label.csv', header=None)
train_label = train_label.to_numpy()

train_label.shape

(700, 1)

In [6]:
path_x = 'C:/Users/kbj/Downloads/data/test/x/'
data_test_x_list = os.listdir('C:/Users/kbj/Downloads/data/test/x/')
x_test_mean = np.array([])
x_test_var = np.array([])
x_test_std = np.array([])
x_test_max = np.array([])
x_test_min = np.array([])

for i in data_test_x_list:
    df = pd.read_csv(path_x+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    x_test_mean = np.append(x_test_mean, mean)
    x_test_var = np.append(x_test_var, var)
    x_test_std = np.append(x_test_std, std)
    x_test_max = np.append(x_test_max, max)
    x_test_min = np.append(x_test_min, min)

x_test_feature = np.concatenate((x_test_mean.reshape(-1,1), x_test_var.reshape(-1,1), x_test_std.reshape(-1,1), x_test_max.reshape(-1,1), x_test_min.reshape(-1,1)), axis=1)
print(x_test_feature.shape)

path_y = 'C:/Users/kbj/Downloads/data/test/y/'
data_test_y_list = os.listdir('C:/Users/kbj/Downloads/data/test/y/')
y_test_mean = np.array([])
y_test_var = np.array([])
y_test_std = np.array([])
y_test_max = np.array([])
y_test_min = np.array([])

for i in data_test_y_list:
    df = pd.read_csv(path_y+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    y_test_mean = np.append(y_test_mean, mean)
    y_test_var = np.append(y_test_var, var)
    y_test_std = np.append(y_test_std, std)
    y_test_max = np.append(y_test_max, max)
    y_test_min = np.append(y_test_min, min)

y_test_feature = np.concatenate((y_test_mean.reshape(-1,1), y_test_var.reshape(-1,1), y_test_std.reshape(-1,1), y_test_max.reshape(-1,1), y_test_min.reshape(-1,1)), axis=1)
print(y_test_feature.shape)

path_z = 'C:/Users/kbj/Downloads/data/test/z/'
data_test_z_list = os.listdir('C:/Users/kbj/Downloads/data/test/z/')
z_test_mean = np.array([])
z_test_var = np.array([])
z_test_std = np.array([])
z_test_max = np.array([])
z_test_min = np.array([])

for i in data_test_z_list:
    df = pd.read_csv(path_z+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    z_test_mean = np.append(z_test_mean, mean)
    z_test_var = np.append(z_test_var, var)
    z_test_std = np.append(z_test_std, std)
    z_test_max = np.append(z_test_max, max)
    z_test_min = np.append(z_test_min, min)

z_test_feature = np.concatenate((z_test_mean.reshape(-1,1), z_test_var.reshape(-1,1), z_test_std.reshape(-1,1), z_test_max.reshape(-1,1), z_test_min.reshape(-1,1)), axis=1)
print(z_test_feature.shape)

path_e = 'C:/Users/kbj/Downloads/data/test/e/'
data_test_e_list = os.listdir('C:/Users/kbj/Downloads/data/test/e/')
e_test_mean = np.array([])
e_test_var = np.array([])
e_test_std = np.array([])
e_test_max = np.array([])
e_test_min = np.array([])

for i in data_test_e_list:
    df = pd.read_csv(path_e+i, header=None)
    mean = np.mean(df.to_numpy())
    var = np.var(df.to_numpy())
    std = np.std(df.to_numpy())
    max = np.max(df.to_numpy())
    min = np.min(df.to_numpy())
    e_test_mean = np.append(e_test_mean, mean)
    e_test_var = np.append(e_test_var, var)
    e_test_std = np.append(e_test_std, std)
    e_test_max = np.append(e_test_max, max)
    e_test_min = np.append(e_test_min, min)

e_test_feature = np.concatenate((e_test_mean.reshape(-1,1), e_test_var.reshape(-1,1), e_test_std.reshape(-1,1), e_test_max.reshape(-1,1), e_test_min.reshape(-1,1)), axis=1)
print(e_test_feature.shape)

#xyz_test_feature = np.sqrt(np.square(x_test_feature[:,0])+np.square(y_test_feature[:,0])+np.square(z_test_feature[:,0]))
#xyz_test_feature = xyz_test_feature.reshape(-1,1)
#all_test_feature = np.concatenate((x_test_feature, y_test_feature, z_test_feature, e_test_feature, xyz_test_feature), axis=1)

all_test_feature = np.concatenate((x_test_feature, y_test_feature, z_test_feature, e_test_feature), axis=1)
print(all_test_feature.shape)

test_label = pd.read_csv('C:/Users/kbj/Downloads/data/test/test_label.csv', header=None)
test_label = test_label.to_numpy()

print(test_label.shape)

(1400, 5)
(1400, 5)
(1400, 5)
(1400, 5)
(1400, 20)
(1400, 1)


In [7]:
print(all_train_feature.shape)
print(train_label.shape)

print(all_test_feature.shape)
print(test_label.shape)

(700, 20)
(700, 1)
(1400, 20)
(1400, 1)


In [14]:
train_x = all_train_feature
train_y = train_label.reshape(-1)
test_x = all_test_feature
test_y = test_label.reshape(-1)

In [15]:
from sklearn.preprocessing import StandardScaler

sc = StandardScaler()
sc.fit(train_x)

x_train_std = sc.transform(train_x)
x_test_std = sc.transform(test_x)

In [16]:
from sklearn.svm import SVC

svm_model = SVC(kernel='rbf', C=8, gamma=0.1)

svm_model.fit(x_train_std, train_y)

SVC(C=8, gamma=0.1)

In [19]:
y_pred = svm_model.predict(x_test_std)

print("prediction accuracy: {:.5f}".format(np.mean(y_pred == test_y)))

prediction accuracy: 0.98357


In [20]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(test_y,y_pred))

[[196   0   1   0   0   0   3]
 [  1 194   4   0   0   0   1]
 [  2   0 194   3   0   0   1]
 [  0   0   0 200   0   0   0]
 [  0   0   0   0 200   0   0]
 [  0   0   0   0   0 200   0]
 [  4   3   0   0   0   0 193]]


In [ ]:
train_x = torch.Tensor(all_train_feature)
train_y = torch.LongTensor(train_label.reshape(-1))
test_x = torch.Tensor(all_test_feature)
test_y = torch.LongTensor(test_label.reshape(-1))

ds_train = TensorDataset(train_x, train_y)
ds_test = TensorDataset(test_x, test_y)

loader_train = DataLoader(ds_train, batch_size=128, shuffle=True)
loader_test = DataLoader(ds_test, shuffle=False)